import os
import enum
import logging
import asyncio
import numpy as np
from dotenv import load_dotenv
from agents.realtime import (
    RealtimeAgent, 
    RealtimeRunner, 
    RealtimeModelSendRawMessage
)
from agents import FunctionTool, RunContextWrapper
from pydantic import BaseModel, Field
from typing import Any, Literal

load_dotenv()
logger = logging.getLogger(__name__)

class OpenAIRealtimeClient:
    def __init__(self, api_key=None, model_name=None, instructions=None, allowed_emotions=None):
        self.api_key = api_key or os.getenv("OPENAI_API_KEY")
        self.model_name = model_name
        self.allowed_emotions = allowed_emotions
        self.instructions = instructions

    async def analyze_stream(self, audio_data, samplerate=24000):
        """
        Stream audio to OpenAI Realtime API using openai-agents and get emotion analysis.
        audio_data: numpy array of audio samples.
        """
        logger.info("Initializing OpenAI Realtime Agent...")
        
        if self.allowed_emotions is None:
            class EmotionArgs(BaseModel):
                emotion: str = Field(
                    description="Der präzise englische Begriff für die klassifizierte Emotion."
                )
                reason: str = Field(
                    description="Eine kurze Begründung der Klassifikation auf Deutsch (maximal 8 Wörter)."
                )
        else:
            EmotionEnum = enum.Enum('EmotionEnum', {e: e for e in self.allowed_emotions})
            class EmotionArgs(BaseModel):
                emotion: EmotionEnum = Field(
                    description="Der präzise englische Begriff für die klassifizierte Emotion."
                )
                reason: str = Field(
                    description="Eine kurze Begründung der Klassifikation auf Deutsch (maximal 8 Wörter)."
                )

        async def run_emotion_record(ctx: RunContextWrapper[Any], args: str) -> str:
            try:
                # Manually parses the JSON string generated by the API
                parsed = EmotionArgs.model_validate_json(args)
                emotion_val = parsed.emotion.value if hasattr(parsed.emotion, 'value') else parsed.emotion
                return f"{{\"emotion\": \"{emotion_val}\", \"reason\": \"{parsed.reason}\"}}"
            except Exception as e:
                # Returning the error as a string allows the model to see what went wrong and correct it in real-time
                return f"Validation Error: You must pick an emotion strictly from the allowed list. Details: {str(e)}"
            
        record_emotion_tool = FunctionTool(
            name="record_emotion",
            description="Speichert das Ergebnis der Emotionsanalyse. (Zwingend aufzurufen)",
            params_json_schema=EmotionArgs.model_json_schema(),
            on_invoke_tool=run_emotion_record,
        )
        
        agent = RealtimeAgent(
            name="EmotionAnalyzer",
            instructions=self.instructions,
            tools=[record_emotion_tool]
        )
        
        model_settings = {
            "tool_choice": "required",
            "turn_detection": None
        }
        if self.model_name is not None:
            model_settings["model_name"] = self.model_name

        runner = RealtimeRunner(
            starting_agent=agent,
            config={
                "model_settings": model_settings
            }
        )
        # --- OLD CONFIGURATION (kept for reference) ---
        # runner = RealtimeRunner(
        #     starting_agent=agent,
        #     config={
        #         "model_settings": {
        #             "model_name": "gpt-realtime-1.5",
        #             "tool_choice": "required",
        #             "turn_detection": None
        #         }
        #     }
        # )
        
        # logger.info("Starting Realtime Session...")
        final_response = None
        
        try:
            # Use a timeout to prevent hanging forever
            async with asyncio.timeout(60):
                async with await runner.run() as session:
                    # logger.info("Connected to OpenAI via openai-agents.")
                    
                    # Ensure audio is mono
                    if len(audio_data.shape) > 1:
                        # logger.info(f"Converting {audio_data.shape[1]}-channel audio to mono...")
                        audio_data = np.mean(audio_data, axis=1)

                    # Convert float32 numpy audio to pcm16 bytes
                    pcm_data = (audio_data * 32767).astype(np.int16).tobytes()
                    
                    # logger.info(f"Sending audio data ({len(pcm_data)} bytes)...")
                    await session.send_audio(pcm_data, commit=True)
                    
                    # Explicitly trigger a response since VAD is disabled
                    await session.model.send_event(RealtimeModelSendRawMessage(
                        message={"type": "response.create"}
                    ))
                    
                    # logger.info("Waiting for response...")
                    
                    async for session_event in session:
                        # Case 1: Capture from specialized history events
                        if session_event.type in ("history_updated", "history_added"):
                            history = getattr(session_event, 'history', []) if session_event.type == "history_updated" else [getattr(session_event, 'item', None)]
                            for item in history:
                                if item and hasattr(item, 'role') and item.role == "assistant":
                                    if hasattr(item, 'content'):
                                        for content_part in item.content:
                                            transcript = getattr(content_part, 'transcript', None)
                                            if transcript:
                                                final_response = transcript

                        # Case 2: Capture from raw server events (very robust)
                        if session_event.type == "raw_model_event":
                            raw_model_event = session_event.data
                            # RealtimeModelRawServerEvent has a .data field which is the raw dict
                            if hasattr(raw_model_event, "data") and isinstance(raw_model_event.data, dict):
                                server_event = raw_model_event.data
                                server_event_type = server_event.get("type")
                                
                                if server_event_type == "response.function_call_arguments.done":
                                    if server_event.get("name") == "record_emotion":
                                        final_response = server_event.get("arguments")
                                
                                if server_event_type == "response.output_item.done":
                                    item = server_event.get("item", {})
                                    if item.get("role") == "assistant":
                                        if item.get("type") == "function_call" and item.get("name") == "record_emotion":
                                            final_response = item.get("arguments")
                                        else:
                                            for part in item.get("content", []):
                                                if part.get("type") == "audio" and part.get("transcript"):
                                                    final_response = part.get("transcript")
                                
                                # Early exit if response is fully done
                                if server_event_type == "response.done":
                                    if final_response:
                                        break

                        if session_event.type == "agent_end":
                            if final_response:
                                break
                        
                        if session_event.type == "error":
                            logger.error(f"Realtime error event: {getattr(session_event, 'error', 'Unknown error')}")
                            break

        except asyncio.TimeoutError:
            logger.error("OpenAI Realtime session timed out.")
        except Exception as e:
            logger.error(f"Error in OpenAI Realtime session: {e}")
                
        return final_response
