STATE = {'local': {'file': None,
           'is_segment': False,
           'model': None,
           'status': 'stopped',
           'tqdm_dict': {}},
 'openai': {'file': None,
            'is_segment': False,
            'model': None,
            'status': 'stopped',
            'tqdm_dict': {}},
 'total_concat_files': 30,
 'total_segments': 758,
 'vram_mb': 0,
 'vram_reserved_mb': 0}
