STATE = {'local': {'file': None,
           'is_phase': False,
           'is_segment': False,
           'model': None,
           'status': 'stopped',
           'tqdm_dict': {}},
 'openai': {'file': 'conv__+436602359202_22-08-2024_10_07_09',
            'is_phase': True,
            'is_segment': False,
            'model': 'openai_realtime_plutchik_2',
            'status': 'processing',
            'tqdm_dict': {'ascii': False,
                          'bar_format': None,
                          'colour': None,
                          'elapsed': 71.75283813476562,
                          'initial': 0,
                          'n': 7,
                          'ncols': 321,
                          'nrows': 21,
                          'postfix': 'conv__+436602359202_22-08-2024_10_07_09',
                          'prefix': 'Running openai_realtime_plutchik_2 '
                                    '(Phases)',
                          'rate': 0.09773328905863253,
                          'total': 30,
                          'unit': 'it',
                          'unit_divisor': 1000,
                          'unit_scale': False}},
 'total_concat_files': 30,
 'total_phases': 140,
 'total_segments': 758,
 'vram_mb': 367,
 'vram_reserved_mb': 15600}
