STATE = {'local': {'file': None,
           'is_segment': False,
           'model': None,
           'status': 'stopped',
           'tqdm_dict': {}},
 'openai': {'file': None,
            'is_segment': False,
            'model': None,
            'status': 'stopped',
            'tqdm_dict': {'ascii': True,
                          'bar_format': None,
                          'colour': None,
                          'elapsed': 0.0,
                          'initial': 8,
                          'n': 8,
                          'ncols': None,
                          'nrows': None,
                          'postfix': 'conv__+436602359202_22-08-2024_10_07_09',
                          'prefix': 'Running openai_realtime_rp (Segments)',
                          'rate': None,
                          'total': 10,
                          'unit': 'it',
                          'unit_divisor': 1000,
                          'unit_scale': False}},
 'total_concat_files': 10,
 'total_segments': 86,
 'vram_mb': 0,
 'vram_reserved_mb': 0}
